output: user.o network.o social_network.o
	g++ user.o network.o social_network.o -o output

user.o: user.cpp
	g++ -c user.cpp -o user.o

network.o: network.cpp
	g++ -c network.cpp -o network.o
	
social_network.o: social_network.cpp
	g++ -c social_network.cpp -o social_network.o